# Generated by Django 2.0.3 on 2018-04-13 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='detiles',
            new_name='comments_detiles',
        ),
    ]
